#!/bin/sh

readlinks() {
    for i in $*; do
	readlink -f $i
    done
}

DATABASE_DIR=$HOME/.cabal/share/hoogle-4.2.13/databases
FINDTXT_DIRS="/usr/lib/ghc-doc/hoogle/ $HOME/.cabal/share/doc/"
HOOGLE=$HOME/.cabal/bin/hoogle

# cleanup
rm -rf $DATABASE_DIR/*

# copy (fake) files
mkdir -p $DATABASE_DIR/download/hackage-cabal
cd $DATABASE_DIR/download && touch hackage-cabal.txt hackage-hoogle.txt haskell-platform.cabal base.txt ghc.txt
#cp /usr/share/hoogle/predownload/keyword.txt $DATABASE_DIR/download/

# new database
$HOOGLE data keyword

# convert
echo -n "Converting databases."
TXTFILES_SYM=`find $FINDTXT_DIRS -name "*.txt"`
TXTFILES=`readlinks $TXTFILES_SYM`
for i in $TXTFILES; do
    echo -n "."
    $HOOGLE convert $i $DATABASE_DIR/`basename $i`.hoo --addlocation >/dev/null 2>&1
done
echo " done"

# combine
cd $DATABASE_DIR/ && $HOOGLE combine *.hoo
